export const pharmacyList = [
  {
    pharmacy: 'Farmacia Susana - Rizal',
    director: 'Mr. Leo A. Tan',
    code: 'SUS',
    dear: 'Mr. Tan',
    title: 'Proprietor',
    address: '50th District, Ozamiz City',
  },
  // {
  //   pharmacy: 'Farmacia Susana - Tinago',
  //   director: 'Mr. Leo A. Tan',
  //   code: 'SUS',
  //   dear: 'Mr. Tan',
  //   title: 'Proprietor',
  //   address: 'Tinago, Ozamiz City',
  // },
  // {
  //   pharmacy: 'Farmacia Susana - Lam-an',
  //   director: 'Mr. Leo A. Tan',
  //   code: 'SUS',
  //   dear: 'Mr. Tan',
  //   title: 'Proprietor',
  //   address: 'Lam-an, Ozamiz City',
  // },
  // {
  //   pharmacy: 'Farmacia Susana - DABA',
  //   director: 'Mr. Leo A. Tan',
  //   code: 'SUS',
  //   dear: 'Mr. Tan',
  //   title: 'Proprietor',
  //   address: 'Maningcol, Ozamiz City',
  // },
  {
    pharmacy: 'J.C. Marave Healthcare Products Trading',
    director: 'Mr. Jason Chiong Marave',
    code: 'GEN',
    dear: 'Mr. Marave',
    title: 'Proprietor',
    address: '50th District, Ozamiz City',
  },
  {
    pharmacy: 'Lourdes Pharmacy - Public Mall San Roque',
    director: 'Mr. Caesar K. Lim',
    code: 'LOUR',
    dear: 'Mr. Lim',
    title: 'Proprietor',
    address: 'Baybay San Roque, Ozamiz City',
  },
  // {
  //   pharmacy: 'Lourdes Pharmacy - Geegee ',
  //   director: 'Mr. Caesar K. Lim',
  //   code: 'LOUR',
  //   dear: 'Mr. Lim',
  //   title: 'Proprietor',
  //   address: 'Tinago, Ozamiz City',
  // },
  // {
  //   pharmacy: 'Lourdes Pharmacy - Catadman-Manabay ',
  //   director: 'Mr. Caesar K. Lim',
  //   code: 'LOUR',
  //   dear: 'Mr. Lim',
  //   title: 'Proprietor',
  //   address: 'Catadman-Manabay, Ozamiz City',
  // },
  {
    pharmacy: 'City Health Office',
    director: 'DR. MARIA FLORELYN DATU YROGIROG',
    code: 'CHO',
    dear: 'DR. YROGIROG',
    title: 'Medical Officer V',
    address: 'Aguada, Ozamiz City',
  },
]

export const hospitalsList = [
  'MUMC',
  'Faith',
  'SPPMC',
  'St.Joseph',
  'St.Padre Pio Dialysis Center',
  'Medina',
  'S.M.Lao',
  'Mr. Ditching Eye Center',
  'Tagaloguin-Adona',
  'It Works',
  'JD Rehabilitation Center',
]

export const supplyCategories = [
  'Foods',
  'Supplies',
  'Office Supplies',
  'Construction Supplies',
  'Janitorial Supplies',
  'Maintenance & Repair Supplies',
  'ICT/Computer Supplies',
  'Vehicle/Transport Supplies',
  'Medical & First Aid Supplies',
  'Printing & Reproduction',
  'Others',
]

export const dswdHospitals = [
  'Mayor Hilarion A. Ramiro Sr. Medical Center',
  'Misamis University Medical Center',
  'Tobias Feliciano Faith General Hospital',
  'St. Joseph General Hospital',
  'Medina General Hospital',
  'S.M. Lao Memorial City General Hospital',
]

export const requestTypes = [
  'MRI',
  'EEG',
  'Medicines',
  'Daily Sustenance',
  'Hospital Bill',
  'Funeral Bill',
  'Financial Assistance',
  'Financial Assistance (Medicine)',
  'Chemotherapy',
  'Other',
]

export const docTypes = [
  'Solicitation / Financial Assistance',
  'Medical Assistance',
  'Courtesy Call',
  'Invitation',
  'Infrastructure Request',
  'Request Endorsement/Applicants',
  'Others',
]

export const docRouting = [
  'Forwarded',
  'Forwarded to Accounting',
  'Forwarded to Agri',
  'Forwarded to Assesors',
  'Forwarded to Atty Cassie',
  'Forwarded to Atty Rhea',
  'Forwarded to BAC',
  'Forwarded to Budget',
  'Forwarded to CADM',
  'Forwarded to CCRO',
  'Forwarded to CDRRMO',
  'Forwarded to CEEDO',
  'Forwarded to CEO',
  'Forwarded to CHO',
  'Forwarded to CHRMO',
  'Forwarded to City Council',
  'Forwarded to COA',
  'Forwarded to CPDO',
  'Forwarded to CSWD',
  'Forwarded to CTO',
  'Forwarded to DILG',
  'Forwarded to GSO',
  'Forwarded to iBPLS',
  'Forwarded to Liga ng mga Barangay',

  'Forwarded to Nutrition',
  'Forwarded to OCM',
  'Forwarded to OCM 4th Floor',
  'Forwarded to OCIT',
  'Forwarded to Permit Div',
  'Forwarded to PNP',
  'Forwarded to SK Fed',
  'Forwarded to SM Lao',
  'Forwarded to Tourism',
  'Forwarded to Vet',
  'Forwarded to Vice Mayor',
  'Received at CADM',
  'Received at OCM',
]

export const documentTypes = [
  { type: 'Business Permit', shortcut: 'BUSS-PER' },
  { type: 'Case', shortcut: 'CASE' },
  { type: 'Certification', shortcut: 'CERT' },
  { type: 'Contract of Service', shortcut: 'COS' },
  { type: 'Cheque', shortcut: 'CHQ' },
  { type: 'DTR', shortcut: 'DTR' },
  { type: 'Disbursement Voucher', shortcut: 'DV' },
  { type: 'Executive Order', shortcut: 'EO' },
  { type: 'IPCR/OPCR', shortcut: 'IPCR/OPCR' },
  { type: 'Letters', shortcut: 'LETTER' },
  { type: 'Leave', shortcut: 'LEAVE' },
  { type: 'Liquidation', shortcut: 'LIQUIDATION' },
  { type: 'Retirement', shortcut: 'RET' },
  { type: 'MOA', shortcut: 'MOA' },
  { type: 'Memorandum Order', shortcut: 'MEMO' },
  { type: 'Notice', shortcut: 'NOTICE' },
  { type: 'Notice of Violation', shortcut: 'NOTI-VIOL' },
  { type: 'Office Order', shortcut: 'OFC-ORD' },
  { type: 'Other Documents', shortcut: 'OTR-DOC' },
  { type: 'Order of Payment', shortcut: 'ORD-PYMT' },
  { type: 'Ordinance', shortcut: 'ORD' },
  { type: 'OBR', shortcut: 'OBR' },
  { type: 'OBR/Payroll', shortcut: 'OBR/PYRL' },
  { type: 'Permit', shortcut: 'PERMIT' },
  { type: 'Project', shortcut: 'PROJ' },
  { type: 'PR/OBR', shortcut: 'PR/OBR' },
  { type: 'Purchase Request', shortcut: 'PR' },
  { type: 'Proposal', shortcut: 'PRPSL' },
  { type: 'Purchase Order', shortcut: 'PO' },
  { type: 'OBR/Reimbursement', shortcut: 'OBR/REIMB' },
  { type: 'Resolution', shortcut: 'RESO' },
  { type: 'Reports', shortcut: 'REPORT' },
  { type: 'Salary Loan', shortcut: 'SAL-LOAN' },
  { type: 'Show Cause', shortcut: 'SHW-CAUSE' },
  { type: 'Special Order', shortcut: 'SO' },
  { type: 'Travel Order', shortcut: 'TO' },
]

export const statusList = [
  { status: 'Disapproved', color: '#e02626' },
  { status: 'For Further Instruction', color: '#997c00' },
  { status: 'For File', color: '#997c00' },
  { status: 'Resolved', color: '#a44508' },
  { status: 'Open', color: '#2154db' },
  { status: 'Approved', color: '#287f00' },
  { status: 'Canceled', color: '#e02626' },
]

export const superAdmins = ['berlcamp@gmail.com', 'berlcampomanes@gmail.com']

export const risOffices = ['OCM', 'DepEd', 'POC']

export const addresses = [
  'Ozamiz, 50th District',
  'Ozamiz, Aguada',
  'Ozamiz, Bacolod',
  'Ozamiz, Bagakay',
  'Ozamiz, Balintawak',
  'Ozamiz, Banadero',
  'Ozamiz, Baybay San Roque',
  'Ozamiz, Baybay Santa Cruz',
  'Ozamiz, Baybay Triunfo',
  'Ozamiz, Bongbong',
  'Ozamiz, Calabayan',
  'Ozamiz, Capucao C.',
  'Ozamiz, Capucao P.',
  'Ozamiz, Carangan',
  'Ozamiz, Carmen',
  'Ozamiz, Catadman-Manabay',
  'Ozamiz, Cavinte',
  'Ozamiz, Cogon',
  'Ozamiz, Dalapang',
  'Ozamiz, Diguan',
  'Ozamiz, Dimaluna',
  'Ozamiz, Doña Consuelo',
  'Ozamiz, Embargo',
  'Ozamiz, Gala',
  'Ozamiz, Gango',
  'Ozamiz, Gotokan Daku',
  'Ozamiz, Gotokan Diot',
  'Ozamiz, Guimad',
  'Ozamiz, Guingona',
  'Ozamiz, Kinuman Norte',
  'Ozamiz, Kinuman Sur',
  'Ozamiz, Labinay',
  'Ozamiz, Labo',
  'Ozamiz, Lam-an',
  'Ozamiz, Liposong',
  'Ozamiz, Litapan',
  'Ozamiz, Malaubang',
  'Ozamiz, Manaka',
  'Ozamiz, Maningcol',
  'Ozamiz, Mentering',
  'Ozamiz, Molicay',
  'Ozamiz, Pantaon',
  'Ozamiz, Pulot',
  'Ozamiz, San Antonio',
  'Ozamiz, Sangay Daku',
  'Ozamiz, Sangay Diot',
  'Ozamiz, Sinuza',
  'Ozamiz, Stimson Abordo',
  'Ozamiz, Tabid',
  'Ozamiz, Tinago',
  'Ozamiz, Trigos',
  'Bonifacio, Bag-ong Anonang',
  'Bonifacio, Bagumbang',
  'Bonifacio, Baybay',
  'Bonifacio, Bolinsong',
  'Bonifacio, Buenavista',
  'Bonifacio, Buracan',
  'Bonifacio, Calolot',
  'Bonifacio, Demetrio Fernan',
  'Bonifacio, Digson',
  'Bonifacio, Dimalco',
  'Bonifacio, Dullan',
  'Bonifacio, Kanaokanao',
  'Bonifacio, Liloan',
  'Bonifacio, Linconan',
  'Bonifacio, Lodiong',
  'Bonifacio, Lower Usugan',
  'Bonifacio, Mapurog',
  'Bonifacio, Migpange',
  'Bonifacio, Montol',
  'Bonifacio, Pisa-an',
  'Bonifacio, Poblacion',
  'Bonifacio, Remedios',
  'Bonifacio, Rufino Lumapas',
  'Bonifacio, Sibuyon',
  'Bonifacio, Tangab',
  'Bonifacio, Tiaman',
  'Bonifacio, Tusik',
  'Bonifacio, Upper Usugan',
  'Clarin, Bernad',
  'Clarin, Bito-on',
  'Clarin, Cabunga-an',
  'Clarin, Canibungan Daku',
  'Clarin, Canibungan Putol',
  'Clarin, Canicapan',
  'Clarin, Dalingap',
  'Clarin, Dela Paz',
  'Clarin, Dolores',
  'Clarin, Gata Daku',
  'Clarin, Gata Diot',
  'Clarin, Guba',
  'Clarin, Kinangay Norte',
  'Clarin, Kinangay Sur',
  'Clarin, Lapasan',
  'Clarin, Lupagan',
  'Clarin, Malibangcao',
  'Clarin, Masabud',
  'Clarin, Mialen',
  'Clarin, Pan-ay',
  'Clarin, Penacio',
  'Clarin, Poblacion I',
  'Clarin, Poblacion II',
  'Clarin, Poblacion III',
  'Clarin, Poblacion IV',
  'Clarin, Sebasi',
  'Clarin, Segatic Daku',
  'Clarin, Segatic Diot',
  'Clarin, Tinacla-an',
  'Don Victoriano Chiongbian, Bagong Clarin',
  'Don Victoriano Chiongbian, Gandawan',
  'Don Victoriano Chiongbian, Lake Duminagat',
  'Don Victoriano Chiongbian, Lalud',
  'Don Victoriano Chiongbian, Lampasan',
  'Don Victoriano Chiongbian, Liboron',
  'Don Victoriano Chiongbian, Maramara',
  'Don Victoriano Chiongbian, Napangan',
  'Don Victoriano Chiongbian, Nueva Vista',
  'Don Victoriano Chiongbian, Petianan',
  'Don Victoriano Chiongbian, Tuno',
  'Tangub, Aquino',
  'Tangub, Balatacan',
  'Tangub, Baluk',
  'Tangub, Banglay',
  'Tangub, Barangay I-City Hall',
  'Tangub, Barangay II-Marilou Annex',
  'Tangub, Barangay III-Market Kalubian',
  'Tangub, Barangay IV-Saint Michael',
  'Tangub, Barangay V-Malubog',
  'Tangub, Barangay VI-Lower Polao',
  'Tangub, Barangay VII-Upper Polao',
  'Tangub, Bintana',
  'Tangub, Bocator',
  'Tangub, Bongabong',
  'Tangub, Caniangan',
  'Tangub, Capalaran',
  'Tangub, Catagan',
  'Tangub, Garang',
  'Tangub, Guinabot',
  'Tangub, Guinalaban',
  'Tangub, Huyohoy',
  'Tangub, Isidro D. Tan',
  'Tangub, Kauswagan',
  'Tangub, Kimat',
  'Tangub, Labuyo',
  'Tangub, Lorenzo Tan',
  'Tangub, Lumban',
  'Tangub, Maloro',
  'Tangub, Manga',
  'Tangub, Mantic',
  'Tangub, Maquilao',
  'Tangub, Matugnaw',
  'Tangub, Migcanaway',
  'Tangub, Minsubong',
  'Tangub, Owayan',
  'Tangub, Paiton',
  'Tangub, Panalsalan',
  'Tangub, Pangabuan',
  'Tangub, Prenza',
  'Tangub, Salimpuno',
  'Tangub, San Antonio',
  'Tangub, San Apolinario',
  'Tangub, San Vicente',
  'Tangub, Santa Cruz',
  'Tangub, Santa Maria',
  'Tangub, Santo Niño',
  'Tangub, Sicot',
  'Tangub, Silanga',
  'Tangub, Silangit',
  'Tangub, Simasay',
  'Tangub, Sumirap',
  'Tangub, Taguite',
  'Tangub, Tituron',
  'Tangub, Tugas',
  'Tangub, Villaba',
  'Tudela, Balon',
  'Tudela, Barra',
  'Tudela, Basirang',
  'Tudela, Bongabong',
  'Tudela, Buenavista',
  'Tudela, Cabol-anonan',
  'Tudela, Cahayag',
  'Tudela, Calambutan Bajo',
  'Tudela, Calambutan Settlement',
  'Tudela, Camating',
  'Tudela, Canibungan Proper',
  'Tudela, Casilak San Agustin',
  'Tudela, Centro Hulpa',
  'Tudela, Centro Napu',
  'Tudela, Centro Upper',
  'Tudela, Duanguican',
  'Tudela, Gala',
  'Tudela, Gumbil',
  'Tudela, Locso-on',
  'Tudela, Maikay',
  'Tudela, Maribojoc',
  'Tudela, Mitugas',
  'Tudela, Nailon',
  'Tudela, Namut',
  'Tudela, Napurog',
  'Tudela, Pan-ay Diot',
  'Tudela, San Nicolas',
  'Tudela, Sebac',
  'Tudela, Silongon',
  'Tudela, Sinuza',
  'Tudela, Taguima',
  'Tudela, Tigdok',
  'Tudela, Yahong',
  'Sinacaban, Cagay-anon',
  'Sinacaban, Camanse',
  'Sinacaban, Colupan Alto',
  'Sinacaban, Colupan Bajo',
  'Sinacaban, Dinas',
  'Sinacaban, Estrella',
  'Sinacaban, Katipunan',
  'Sinacaban, Libertad Alto',
  'Sinacaban, Libertad Bajo',
  'Sinacaban, Poblacion',
  'Sinacaban, San Isidro Alto',
  'Sinacaban, San Isidro Bajo',
  'Sinacaban, San Lorenzo Ruiz',
  'Sinacaban, San Vicente',
  'Sinacaban, Señor',
  'Sinacaban, Sinonoc',
  'Sinacaban, Tipan',
]
