export const pharmacyList = [
  {
    pharmacy: 'Farmacia Susana - Rizal',
    director: 'Mr. Leo A. Tan',
    code: 'SUS',
    dear: 'Mr. Tan',
    title: 'Proprietor',
    address: '50th District, Ozamiz City',
  },
  // {
  //   pharmacy: 'Farmacia Susana - Tinago',
  //   director: 'Mr. Leo A. Tan',
  //   code: 'SUS',
  //   dear: 'Mr. Tan',
  //   title: 'Proprietor',
  //   address: 'Tinago, Ozamiz City',
  // },
  // {
  //   pharmacy: 'Farmacia Susana - Lam-an',
  //   director: 'Mr. Leo A. Tan',
  //   code: 'SUS',
  //   dear: 'Mr. Tan',
  //   title: 'Proprietor',
  //   address: 'Lam-an, Ozamiz City',
  // },
  // {
  //   pharmacy: 'Farmacia Susana - DABA',
  //   director: 'Mr. Leo A. Tan',
  //   code: 'SUS',
  //   dear: 'Mr. Tan',
  //   title: 'Proprietor',
  //   address: 'Maningcol, Ozamiz City',
  // },
  {
    pharmacy: 'J.C. Marave Healthcare Products Trading',
    director: 'Mr. Jason Chiong Marave',
    code: 'GEN',
    dear: 'Mr. Marave',
    title: 'Proprietor',
    address: '50th District, Ozamiz City',
  },
  {
    pharmacy: 'Lourdes Pharmacy - Public Mall San Roque',
    director: 'Mr. Caesar K. Lim',
    code: 'LOUR',
    dear: 'Mr. Lim',
    title: 'Proprietor',
    address: 'Baybay San Roque, Ozamiz City',
  },
  // {
  //   pharmacy: 'Lourdes Pharmacy - Geegee ',
  //   director: 'Mr. Caesar K. Lim',
  //   code: 'LOUR',
  //   dear: 'Mr. Lim',
  //   title: 'Proprietor',
  //   address: 'Tinago, Ozamiz City',
  // },
  // {
  //   pharmacy: 'Lourdes Pharmacy - Catadman-Manabay ',
  //   director: 'Mr. Caesar K. Lim',
  //   code: 'LOUR',
  //   dear: 'Mr. Lim',
  //   title: 'Proprietor',
  //   address: 'Catadman-Manabay, Ozamiz City',
  // },
  {
    pharmacy: 'City Health Office',
    director: 'DR. MARIA FLORELYN DATU YROGIROG',
    code: 'CHO',
    dear: 'DR. YROGIROG',
    title: 'Medical Officer V',
    address: 'Aguada, Ozamiz City',
  },
]

export const hospitalsList = [
  'MUMC',
  'Faith',
  'SPPMC',
  'St.Joseph',
  'St.Padre Pio Dialysis Center',
  'Medina',
  'S.M.Lao',
  'Mr. Ditching Eye Center',
  'Tagaloguin-Adona',
  'It Works',
  'JD Rehabilitation Center',
]

export const dswdHospitals = [
  'Mayor Hilarion A. Ramiro Sr. Medical Center',
  'Misamis University Medical Center',
  'Tobias Feliciano Faith General Hospital',
  'St. Joseph General Hospital',
  'Medina General Hospital',
]

export const requestTypes = [
  'MRI',
  'EEG',
  'Medicines',
  'Daily Sustenance',
  'Hospital Bill',
  'Funeral Bill',
  'Financial Assistance',
  'Financial Assistance (Medicine)',
  'Chemotherapy',
  'Other',
]

export const docTypes = [
  'Solicitation / Financial Assistance',
  'Medical Assistance',
  'Courtesy Call',
  'Invitation',
  'Infrastructure Request',
  'Request Endorsement/Applicants',
  'Others',
]

export const docRouting = [
  'Forwarded',
  'Forwarded to Accounting',
  'Forwarded to Agri',
  'Forwarded to Assesors',
  'Forwarded to Atty Cassie',
  'Forwarded to Atty Rhea',
  'Forwarded to BAC',
  'Forwarded to Budget',
  'Forwarded to CADM',
  'Forwarded to CCRO',
  'Forwarded to CDRRMO',
  'Forwarded to CEEDO',
  'Forwarded to CEO',
  'Forwarded to CHO',
  'Forwarded to CHRMO',
  'Forwarded to COA',
  'Forwarded to CPDO',
  'Forwarded to CSWD',
  'Forwarded to CTO',
  'Forwarded to GSO',
  'Forwarded to Nutrition',
  'Forwarded to OCM',
  'Forwarded to OCIT',
  'Forwarded to Permit Div',
  'Forwarded to SM Lao',
  'Forwarded to Tourism',
  'Forwarded to Vet',
  'Received at CADM',
  'Received at OCM',
]

export const documentTypes = [
  { type: 'Business Permit', shortcut: 'BUSS-PER' },
  { type: 'Case', shortcut: 'CASE' },
  { type: 'Certification', shortcut: 'CERT' },
  { type: 'Contract of Service', shortcut: 'COS' },
  { type: 'Cheque', shortcut: 'CHQ' },
  { type: 'DTR', shortcut: 'DTR' },
  { type: 'Disbursement Voucher', shortcut: 'DV' },
  { type: 'Executive Order', shortcut: 'EO' },
  { type: 'IPCR/OPCR', shortcut: 'IPCR/OPCR' },
  { type: 'Letters', shortcut: 'LETTER' },
  { type: 'Leave', shortcut: 'LEAVE' },
  { type: 'Liquidation', shortcut: 'LIQUIDATION' },
  { type: 'Retirement', shortcut: 'RET' },
  { type: 'MOA', shortcut: 'MOA' },
  { type: 'Memorandum Order', shortcut: 'MEMO' },
  { type: 'Notice', shortcut: 'NOTICE' },
  { type: 'Notice of Violation', shortcut: 'NOTI-VIOL' },
  { type: 'Office Order', shortcut: 'OFC-ORD' },
  { type: 'Other Documents', shortcut: 'OTR-DOC' },
  { type: 'Order of Payment', shortcut: 'ORD-PYMT' },
  { type: 'Ordinance', shortcut: 'ORD' },
  { type: 'OBR', shortcut: 'OBR' },
  { type: 'OBR/Payroll', shortcut: 'OBR/PYRL' },
  { type: 'Permit', shortcut: 'PERMIT' },
  { type: 'Project', shortcut: 'PROJ' },
  { type: 'PR/OBR', shortcut: 'PR/OBR' },
  { type: 'Purchase Request', shortcut: 'PR' },
  { type: 'Proposal', shortcut: 'PRPSL' },
  { type: 'Purchase Order', shortcut: 'PO' },
  { type: 'OBR/Reimbursement', shortcut: 'OBR/REIMB' },
  { type: 'Resolution', shortcut: 'RESO' },
  { type: 'Reports', shortcut: 'REPORT' },
  { type: 'Salary Loan', shortcut: 'SAL-LOAN' },
  { type: 'Show Cause', shortcut: 'SHW-CAUSE' },
  { type: 'Special Order', shortcut: 'SO' },
  { type: 'Travel Order', shortcut: 'TO' },
]

export const statusList = [
  { status: 'Disapproved', color: '#e02626' },
  { status: 'For Further Instruction', color: '#997c00' },
  { status: 'For File', color: '#997c00' },
  { status: 'Resolved', color: '#a44508' },
  { status: 'Open', color: '#2154db' },
  { status: 'Approved', color: '#287f00' },
  { status: 'Canceled', color: '#e02626' },
]

export const superAdmins = ['berlcamp@gmail.com', 'berlcampomanes@gmail.com']

export const risOffices = ['OCM', 'DepEd', 'POC']
